### ISSUE TITLE
ALL THE DATA CAN BE ACCESSED DIRECTLY!!!

### ISSUE THREAD

**Issue by aakashpothepalli** [naseerx/Flutter-Todo-App#1]
By just adding few lines of code, I can easily access all the data!
Please take appropriate security measures such as role based access to protect users data.
![image](https://github.com/naseerx/Flutter-Todo-App/assets/19583729/5046f0ee-b90f-4eee-8652-d105e1f1b007)
![image](https://github.com/naseerx/Flutter-Todo-App/assets/19583729/5ba6ba93-1fe9-4aed-8086-80dc4930ad9c)

**Comment by naseerx** [comment]
Hi @aakashpothepalli,

Thank you so much for bringing this to my attention. I take the security of our users' data very seriously, and your input is invaluable. I've reviewed the issue and implemented updated security rules to address the concerns you've raised. If you have any further suggestions or notice anything else, please feel free to contribute. Your vigilance helps us make our project more secure for everyone.

Thanks

**Comment by naseerx** [comment]
This issue has been solved, Thanks @aakashpothepalli for his suggestion
